# Generated by Django 2.0.5 on 2018-06-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=128)),
                ('task_info', models.TextField()),
                ('actual_date', models.DateTimeField()),
                ('status', models.CharField(max_length=128)),
            ],
        ),
    ]
